apiVersion: terraform.core.weave.works/v1beta1
kind: Terraform
metadata:
  name: iac-instance-ec2
  namespace: flux-system
spec:
  path: ./
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: iac-instance-ec2
  secretRef:
    name: aws-credentials
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_SECRET_ACCESS_KEY
