apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: iac-instance-ec2
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/govinda777/iac_instance_ec2
